- name: Assertions
  assert:
    that:
      - k8s_primary_master_name is defined
  tags:
    - apply
    - delete


- name: Check if host uses NetworkManager
  stat:
    path: "{{ k8s_calico_netmgr_path }}"
  register: _netmgr
  tags:
    - apply
    - delete


- name: Create NetworkManager configuration directory
  file:
    path: "{{ k8s_calico_netmgr_path }}/conf.d/"
    state: directory
  when:
    - _netmgr.stat.isdir is defined and _netmgr.stat.isdir
  tags:
    - apply


- name: Template Calico configuration for NetworkManager
  template:
    src: calico.conf.j2
    dest: "{{ k8s_calico_netmgr_path }}/conf.d/calico.conf"
  when:
    - _netmgr.stat.isdir is defined and _netmgr.stat.isdir
  tags:
    - apply


- name: Apply Calico
  k8s:
    definition: "{{ lookup('url', k8s_calico_manifest_url, split_lines=False) }}"
    state: present
    apply: yes
    force: yes
  when:
    - inventory_hostname == k8s_primary_master_name
  tags:
    - apply


- name: Delete Calico
  k8s:
    definition: "{{ lookup('url', k8s_calico_manifest_url, split_lines=False) }}"
    state: absent
  ignore_errors: yes
  when:
    - inventory_hostname == k8s_primary_master_name
  tags:
    - delete


- name: Remove Calico configuration for NetworkManager
  file:
    path: "{{ k8s_calico_netmgr_path }}/conf.d/calico.conf"
    state: absent
  when:
    - _netmgr.stat.isdir is defined and _netmgr.stat.isdir
  tags:
    - delete


- name: Collect host ip links
  shell: >
    ip -json link
  register: _host_links
  tags:
    - delete


- name: Delete remanent Calico links
  shell: |
    ifconfig down "{{ item.ifname }}"
    ip link delete "{{ item.ifname }}"
  when:
    - item.ifname is match("^(br\-|cali)([0-9a-z])+")
  with_items: "{{ _host_links.stdout | from_json }}"
  tags:
    - delete


- name: Delete remanent Calico configuration files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/cni/net.d/10-calico.conflist"
    - "/etc/cni/net.d/calico-kubeconfig"
  tags:
    - delete
